sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: #
    password: #

  redis:
    host: localhost
    port: 6379
    password: #
    database: # database编号


  wechat:
    appid: #
    secret: #

